### ISSUE TITLE
TimeZone Changes

### ISSUE THREAD

**Issue by danielharrelson** [winemug/omnipy#28]
I don't see anything in the documentation about timezone changes.

How does this work for the Pod?

I have a trip in about 2 weeks, and since I'll be traveling back in time 3 hours, I'm curious how to deal with this.

**Comment by dexdan** [comment]
Agree it would be good to include something in the FAQ. I'm not totally sure though of the answer to your question....

I think the time is taken from your android device when the pod is set. I'm not sure what happens if you subsequently change the time on your phone though and what happens if the profile is then updated. I think nightscout and local profiles may behave differently....

Hopefully @winemug will help clarify

**Comment by danielharrelson** [comment]
So, this is what I did. Whether or not it's appropriate, I don't know but it seemed to work.

Setup a NightScout profile with the appropriate information (TimeZone, Basals, I:C, ISF) and saved it as a new name.

Flight took off from EST, when I landed in PST my phone time updated. I pulled the new NightScout profile and set it.

Within a few minutes saw a message that basal rates had been updated.

Everything worked as planned/expected. When I flew back from PST to EST, I switched profiles again with the appropriate profile.
